name: Python Application Workflow

on: [push]

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        # An action is a reusable piece of code that can perform a specific task, like checking out your code, setting up a programming language environment, deploying your code, and so on.
        # The actions/ part of uses: actions/checkout@v2 refers to the GitHub organization that maintains the action. In this case, actions is the official GitHub organization that maintains many common actions. checkout is the name of the action, and @v2 specifies the version of the action to use.
        # Actions can be defined in your own repository, in a public repository, or in a Docker image, and they can be written in any language that can run on GitHub-hosted runners.
        # let's build own action
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r myapp/requirements.txt

      - name: Run tests
        run: python3 myapp/tests.py

      - name: Run application
        run: python3 myapp/main.py

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/your/app
            git pull
            pip install -r requirements.txt
            python3 main.py
